title: Sang-il Oum (엄상일)
description: A mathematician at the IBS Discrete Mathematics Group.
url: "https://sangiloum.github.io"
baseurl: ""
timezone: "Asia/Seoul"
theme: minima
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate-v2

collections:
  papers:
    output: false
    sort_by: sort_key

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_field: "date"
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "category-archive.html"
    permalink: "/blog/category/:cat/"
  tags:
    enabled: false
  collections:
    enabled: false

jekyll-archives:
  enabled:
    - year
  layouts:
    year: year-archive
  permalinks:
    year: "/:year/"

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
  - migration
  - _site
  - _site (1)
